export type LessonComponentNote = {
  label: string;
  note: string;
};

export type LessonSimulationBlueprint = {
  key: string;
  simulationType: string;
  focus: string;
  components: LessonComponentNote[];
  matched?: boolean;
};

function normalize(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/Ã„â€˜/g, 'd')
    .replace(/Ã„Â/g, 'D')
    .toLowerCase()
    .trim();
}

const BLUEPRINTS: LessonSimulationBlueprint[] = [
  { key: 'chuyen dong thang deu', simulationType: 'linear-motion-3d', focus: 'Theo dÃƒÂµi vÃ¡Â»â€¹ trÃƒÂ­, mÃ¡Â»â€˜c tÃ¡Â»Âa Ã„â€˜Ã¡Â»â„¢ vÃƒÂ  vectÃ†Â¡ vÃ¡ÂºÂ­n tÃ¡Â»â€˜c khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.', components: [{ label: 'Xe trÃ†Â°Ã¡Â»Â£t', note: 'VÃ¡ÂºÂ­t khÃ¡ÂºÂ£o sÃƒÂ¡t chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng Ã„â€˜Ã¡Â»Âu trÃƒÂªn ray thÃ¡ÂºÂ³ng.' }, { label: 'Ray chuÃ¡ÂºÂ©n', note: 'TrÃ¡Â»Â¥c chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng Ã„â€˜Ã¡Â»Æ’ Ã„â€˜Ã¡Â»Âc tÃ¡Â»Âa Ã„â€˜Ã¡Â»â„¢ theo thÃ¡Â»Âi gian.' }, { label: 'VectÃ†Â¡ v', note: 'ChÃ¡Â»â€° hÃ†Â°Ã¡Â»â€ºng chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng vÃƒÂ  Ã„â€˜Ã¡Â»â„¢ lÃ¡Â»â€ºn vÃ¡ÂºÂ­n tÃ¡Â»â€˜c khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.' }] },
  { key: 'chuyen dong thang bien doi deu', simulationType: 'accelerated-motion-3d', focus: 'Quan sÃƒÂ¡t Ã„â€˜Ã¡Â»â€œng thÃ¡Â»Âi quÃƒÂ£ng Ã„â€˜Ã†Â°Ã¡Â»Âng, vÃ¡ÂºÂ­n tÃ¡Â»â€˜c vÃƒÂ  gia tÃ¡Â»â€˜c.', components: [{ label: 'Xe tÃ„Æ’ng tÃ¡Â»â€˜c', note: 'VÃ¡ÂºÂ­t chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng thÃ¡ÂºÂ³ng cÃƒÂ³ gia tÃ¡Â»â€˜c khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.' }, { label: 'VectÃ†Â¡ a', note: 'Gia tÃ¡Â»â€˜c lÃƒÂ m vÃ¡ÂºÂ­n tÃ¡Â»â€˜c thay Ã„â€˜Ã¡Â»â€¢i Ã„â€˜Ã¡Â»Âu theo thÃ¡Â»Âi gian.' }, { label: 'MÃ¡Â»â€˜c thÃ¡Â»Âi gian', note: 'DÃƒÂ¹ng Ã„â€˜Ã¡Â»Æ’ so sÃƒÂ¡nh Ã„â€˜Ã¡Â»â„¢ dÃ¡Â»Âi Ã¡Â»Å¸ cÃƒÂ¡c thÃ¡Â»Âi Ã„â€˜iÃ¡Â»Æ’m khÃƒÂ¡c nhau.' }] },
  { key: 'su roi tu do', simulationType: 'free-fall-3d', focus: 'Ã„ÂÃ¡Â»Âc chiÃ¡Â»Âu cao, vÃ¡ÂºÂ­n tÃ¡Â»â€˜c rÃ†Â¡i vÃƒÂ  Ã¡ÂºÂ£nh hÃ†Â°Ã¡Â»Å¸ng cÃ¡Â»Â§a g.', components: [{ label: 'VÃ¡ÂºÂ­t rÃ†Â¡i', note: 'KhÃ¡Â»â€˜i nhÃ¡Â»Â chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng thÃ¡ÂºÂ³ng Ã„â€˜Ã¡Â»Â©ng dÃ†Â°Ã¡Â»â€ºi tÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â§a trÃ¡Â»Âng lÃ¡Â»Â±c.' }, { label: 'ThÃƒÂ¡p Ã„â€˜o', note: 'MÃ¡Â»â€˜c chia Ã„â€˜Ã¡Â»â„¢ Ã„â€˜Ã¡Â»Æ’ Ã„â€˜Ã¡Â»Âc Ã„â€˜Ã¡Â»â„¢ cao vÃƒÂ  quÃƒÂ£ng rÃ†Â¡i.' }, { label: 'Gia tÃ¡Â»â€˜c g', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ chi phÃ¡Â»â€˜i tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ tÃ„Æ’ng cÃ¡Â»Â§a vÃ¡ÂºÂ­n tÃ¡Â»â€˜c rÃ†Â¡i.' }] },
  { key: 'chuyen dong tron deu', simulationType: 'circular-motion-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh bÃƒÂ¡n kÃƒÂ­nh quÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o, tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ gÃƒÂ³c vÃƒÂ  gia tÃ¡Â»â€˜c hÃ†Â°Ã¡Â»â€ºng tÃƒÂ¢m.', components: [{ label: 'Rotor quay', note: 'TÃƒÂ¢m quay cÃ¡Â»â€˜ Ã„â€˜Ã¡Â»â€¹nh tÃ¡ÂºÂ¡o quÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o trÃƒÂ²n Ã„â€˜Ã¡Â»Âu.' }, { label: 'BÃƒÂ¡n kÃƒÂ­nh r', note: 'KhoÃ¡ÂºÂ£ng cÃƒÂ¡ch tÃ¡Â»Â« tÃƒÂ¢m tÃ¡Â»â€ºi vÃ¡ÂºÂ­t chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'Gia tÃ¡Â»â€˜c hÃ†Â°Ã¡Â»â€ºng tÃƒÂ¢m', note: 'LuÃƒÂ´n hÃ†Â°Ã¡Â»â€ºng vÃƒÂ o tÃƒÂ¢m Ã„â€˜Ã¡Â»Æ’ giÃ¡Â»Â¯ vÃ¡ÂºÂ­t trÃƒÂªn quÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o trÃƒÂ²n.' }] },
  { key: 'tong hop va phan tich luc', simulationType: 'force-decomposition-3d', focus: 'TÃƒÂ¡ch lÃ¡Â»Â±c theo trÃ¡Â»Â¥c vÃƒÂ  nhÃƒÂ¬n hÃ¡Â»Â£p lÃ¡Â»Â±c ngay trÃƒÂªn hÃƒÂ¬nh.', components: [{ label: 'VectÃ†Â¡ lÃ¡Â»Â±c thÃƒÂ nh phÃ¡ÂºÂ§n', note: 'CÃƒÂ¡c lÃ¡Â»Â±c tÃƒÂ¡c dÃ¡Â»Â¥ng riÃƒÂªng rÃ¡ÂºÂ½ trÃƒÂªn cÃƒÂ¹ng mÃ¡Â»â„¢t vÃ¡ÂºÂ­t.' }, { label: 'TrÃ¡Â»Â¥c phÃƒÂ¢n tÃƒÂ­ch', note: 'HÃ¡Â»â€¡ trÃ¡Â»Â¥c chuÃ¡ÂºÂ©n Ã„â€˜Ã¡Â»Æ’ chiÃ¡ÂºÂ¿u lÃ¡Â»Â±c theo phÃ†Â°Ã†Â¡ng thuÃ¡ÂºÂ­n tiÃ¡Â»â€¡n.' }, { label: 'HÃ¡Â»Â£p lÃ¡Â»Â±c', note: 'VectÃ†Â¡ tÃ¡Â»â€¢ng tÃ¡ÂºÂ¡o nÃƒÂªn tÃƒÂ¡c dÃ¡Â»Â¥ng tÃ†Â°Ã†Â¡ng Ã„â€˜Ã†Â°Ã†Â¡ng lÃƒÂªn vÃ¡ÂºÂ­t.' }] },
  { key: 'ba dinh luat newton', simulationType: 'newton-laws-3d', focus: 'GÃ¡ÂºÂ¯n quan hÃ¡Â»â€¡ giÃ¡Â»Â¯a lÃ¡Â»Â±c tÃ¡Â»â€¢ng hÃ¡Â»Â£p, khÃ¡Â»â€˜i lÃ†Â°Ã¡Â»Â£ng vÃƒÂ  gia tÃ¡Â»â€˜c.', components: [{ label: 'Xe chÃ¡Â»â€¹u lÃ¡Â»Â±c', note: 'VÃ¡ÂºÂ­t mÃ¡ÂºÂ«u Ã„â€˜Ã¡Â»Æ’ quan sÃƒÂ¡t phÃ¡ÂºÂ£n Ã¡Â»Â©ng khi cÃƒÂ³ lÃ¡Â»Â±c kÃƒÂ©o vÃƒÂ  lÃ¡Â»Â±c cÃ¡ÂºÂ£n.' }, { label: 'LÃ¡Â»Â±c kÃƒÂ©o', note: 'NguyÃƒÂªn nhÃƒÂ¢n trÃ¡Â»Â±c tiÃ¡ÂºÂ¿p gÃƒÂ¢y biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'PhÃ¡ÂºÂ£n lÃ¡Â»Â±c vÃƒÂ  ma sÃƒÂ¡t', note: 'CÃƒÂ¡c lÃ¡Â»Â±c Ã„â€˜i kÃƒÂ¨m giÃƒÂºp Ã„â€˜Ã¡Â»Âc rÃƒÂµ cÃƒÂ¢n bÃ¡ÂºÂ±ng hay mÃ¡ÂºÂ¥t cÃƒÂ¢n bÃ¡ÂºÂ±ng lÃ¡Â»Â±c.' }] },
  { key: 'luc hap dan', simulationType: 'gravity-orbit-3d', focus: 'NhÃƒÂ¬n tÃ†Â°Ã†Â¡ng tÃƒÂ¡c hÃ¡ÂºÂ¥p dÃ¡ÂºÂ«n nhÃ†Â° lÃ¡Â»Â±c hÃ†Â°Ã¡Â»â€ºng tÃƒÂ¢m trong hÃ¡Â»â€¡ hai vÃ¡ÂºÂ­t.', components: [{ label: 'ThiÃƒÂªn thÃ¡Â»Æ’ lÃ¡Â»â€ºn', note: 'NguÃ¡Â»â€œn gÃƒÂ¢y ra trÃ†Â°Ã¡Â»Âng hÃ¡ÂºÂ¥p dÃ¡ÂºÂ«n chÃƒÂ­nh.' }, { label: 'VÃ¡ÂºÂ­t quay', note: 'KhÃ¡Â»â€˜i nhÃ¡Â»Â chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng dÃ†Â°Ã¡Â»â€ºi tÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â§a lÃ¡Â»Â±c hÃ¡ÂºÂ¥p dÃ¡ÂºÂ«n.' }, { label: 'QuÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o', note: 'Ã„ÂÃ†Â°Ã¡Â»Âng Ã„â€˜i biÃ¡Â»Æ’u diÃ¡Â»â€¦n kÃ¡ÂºÂ¿t quÃ¡ÂºÂ£ cÃƒÂ¢n bÃ¡ÂºÂ±ng giÃ¡Â»Â¯a quÃƒÂ¡n tÃƒÂ­nh vÃƒÂ  lÃ¡Â»Â±c hÃƒÂºt.' }] },
  { key: 'luc ma sat', simulationType: 'friction-plane-3d', focus: 'So sÃƒÂ¡nh xu hÃ†Â°Ã¡Â»â€ºng trÃ†Â°Ã¡Â»Â£t vÃ¡Â»â€ºi ma sÃƒÂ¡t giÃ¡Â»Â¯ vÃ¡ÂºÂ­t.', components: [{ label: 'KhÃ¡Â»â€˜i trÃ†Â°Ã¡Â»Â£t', note: 'VÃ¡ÂºÂ­t Ã„â€˜Ã¡ÂºÂ·t trÃƒÂªn mÃ¡ÂºÂ·t phÃ¡ÂºÂ³ng nghiÃƒÂªng Ã„â€˜Ã¡Â»Æ’ theo dÃƒÂµi chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'MÃ¡ÂºÂ·t tiÃ¡ÂºÂ¿p xÃƒÂºc', note: 'BÃ¡Â»Â mÃ¡ÂºÂ·t sinh lÃ¡Â»Â±c ma sÃƒÂ¡t khi vÃ¡ÂºÂ­t cÃƒÂ³ xu hÃ†Â°Ã¡Â»â€ºng trÃ†Â°Ã¡Â»Â£t.' }, { label: 'HÃ¡Â»â€¡ sÃ¡Â»â€˜ ÃŽÂ¼', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh ma sÃƒÂ¡t lÃ¡Â»â€ºn hay nhÃ¡Â»Â.' }] },
  { key: 'luc dan hoi', simulationType: 'spring-3d', focus: 'LiÃƒÂªn hÃ¡Â»â€¡ Ã„â€˜Ã¡Â»â„¢ biÃ¡ÂºÂ¿n dÃ¡ÂºÂ¡ng vÃ¡Â»â€ºi lÃ¡Â»Â±c Ã„â€˜ÃƒÂ n hÃ¡Â»â€œi.', components: [{ label: 'LÃƒÂ² xo', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ Ã„â€˜ÃƒÂ n hÃ¡Â»â€œi co giÃƒÂ£n quanh vÃ¡Â»â€¹ trÃƒÂ­ tÃ¡Â»Â± nhiÃƒÂªn.' }, { label: 'VÃ¡ÂºÂ­t nÃ¡ÂºÂ·ng', note: 'KhÃ¡Â»â€˜i lÃ†Â°Ã¡Â»Â£ng lÃƒÂ m lÃƒÂ² xo biÃ¡ÂºÂ¿n dÃ¡ÂºÂ¡ng vÃƒÂ  dao Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'Ã„ÂÃ¡Â»â„¢ dÃ¡Â»Âi x', note: 'BiÃ¡ÂºÂ¿n Ã„â€˜iÃ¡Â»Âu khiÃ¡Â»Æ’n lÃ¡Â»Â±c kÃƒÂ©o vÃ¡Â»Â theo Ã„â€˜Ã¡Â»â€¹nh luÃ¡ÂºÂ­t Hooke.' }] },
  { key: 'cong va cong suat', simulationType: 'newton-laws-3d', focus: 'NhÃƒÂ¬n vÃ¡ÂºÂ­t Ã„â€˜Ã†Â°Ã¡Â»Â£c kÃƒÂ©o Ã„â€˜i Ã„â€˜Ã¡Â»Æ’ gÃ¡ÂºÂ¯n cÃƒÂ´ng, lÃ¡Â»Â±c vÃƒÂ  vÃ¡ÂºÂ­n tÃ¡Â»â€˜c.', components: [{ label: 'VÃ¡ÂºÂ­t dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n', note: 'Ã„ÂÃ¡Â»â€˜i tÃ†Â°Ã¡Â»Â£ng nhÃ¡ÂºÂ­n cÃƒÂ´ng khi lÃ¡Â»Â±c lÃƒÂ m vÃ¡ÂºÂ­t dÃ¡Â»Âi chÃ¡Â»â€”.' }, { label: 'LÃ¡Â»Â±c tÃƒÂ¡c dÃ¡Â»Â¥ng', note: 'TÃƒÂ¡c nhÃƒÂ¢n sinh cÃƒÂ´ng theo phÃ†Â°Ã†Â¡ng dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n.' }, { label: 'CÃƒÂ´ng suÃ¡ÂºÂ¥t', note: 'MÃ¡Â»Â©c Ã„â€˜Ã¡Â»â„¢ thÃ¡Â»Â±c hiÃ¡Â»â€¡n cÃƒÂ´ng trong mÃ¡Â»â„¢t Ã„â€˜Ã†Â¡n vÃ¡Â»â€¹ thÃ¡Â»Âi gian.' }] },
  { key: 'dong nang', simulationType: 'accelerated-motion-3d', focus: 'Ã„ÂÃ¡Â»Âc tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ vÃƒÂ  liÃƒÂªn hÃ¡Â»â€¡ trÃ¡Â»Â±c tiÃ¡ÂºÂ¿p vÃ¡Â»â€ºi Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng.', components: [{ label: 'KhÃ¡Â»â€˜i chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng', note: 'VÃ¡ÂºÂ­t cÃƒÂ³ tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ cÃƒÂ ng lÃ¡Â»â€ºn thÃƒÂ¬ Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng cÃƒÂ ng tÃ„Æ’ng.' }, { label: 'VÃ¡ÂºÂ­n tÃ¡Â»â€˜c tÃ¡Â»Â©c thÃ¡Â»Âi', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh trÃ¡Â»Â±c tiÃ¡ÂºÂ¿p Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng.' }, { label: 'MÃ¡Â»â€˜c so sÃƒÂ¡nh', note: 'GiÃƒÂºp quan sÃƒÂ¡t sÃ¡Â»Â± biÃ¡ÂºÂ¿n thiÃƒÂªn Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng khi vÃ¡ÂºÂ­n tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â€¢i.' }] },
  { key: 'the nang', simulationType: 'gravity-orbit-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh vÃ¡Â»â€¹ trÃƒÂ­ trong trÃ†Â°Ã¡Â»Âng lÃ¡Â»Â±c quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh thÃ¡ÂºÂ¿ nÃ„Æ’ng.', components: [{ label: 'MÃ¡Â»â€˜c thÃ¡ÂºÂ¿ nÃ„Æ’ng', note: 'VÃ¡Â»â€¹ trÃƒÂ­ chÃ¡Â»Ân lÃƒÂ m chuÃ¡ÂºÂ©n so sÃƒÂ¡nh nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng.' }, { label: 'VÃ¡ÂºÂ­t trong trÃ†Â°Ã¡Â»Âng lÃ¡Â»Â±c', note: 'ThÃ¡ÂºÂ¿ nÃ„Æ’ng thay Ã„â€˜Ã¡Â»â€¢i khi vÃ¡ÂºÂ­t Ã„â€˜Ã¡Â»â€¢i vÃ¡Â»â€¹ trÃƒÂ­.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng mÃ¡Â»Â©c cao Ã„â€˜Ã¡Â»â„¢', note: 'GÃ¡Â»Â£i trÃ¡Â»Â±c giÃƒÂ¡c vÃ¡Â»Â thÃ¡ÂºÂ¿ nÃ„Æ’ng tÃ„Æ’ng giÃ¡ÂºÂ£m theo vÃ¡Â»â€¹ trÃƒÂ­.' }] },
  { key: 'co nang', simulationType: 'pendulum-3d', focus: 'Quan sÃƒÂ¡t trao Ã„â€˜Ã¡Â»â€¢i giÃ¡Â»Â¯a Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng vÃƒÂ  thÃ¡ÂºÂ¿ nÃ„Æ’ng.', components: [{ label: 'VÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng', note: 'ChuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng qua lÃ¡ÂºÂ¡i Ã„â€˜Ã¡Â»Æ’ nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng luÃƒÂ¢n phiÃƒÂªn biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i.' }, { label: 'BiÃƒÂªn vÃƒÂ  vÃ¡Â»â€¹ trÃƒÂ­ cÃƒÂ¢n bÃ¡ÂºÂ±ng', note: 'Hai vÃƒÂ¹ng Ã„â€˜iÃ¡Â»Æ’n hÃƒÂ¬nh Ã„â€˜Ã¡Â»Æ’ Ã„â€˜Ã¡Â»Âc thÃ¡ÂºÂ¿ nÃ„Æ’ng cÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ¡i vÃƒÂ  Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng cÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ¡i.' }, { label: 'TÃ¡Â»â€¢ng cÃ†Â¡ nÃ„Æ’ng', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng gÃ¡ÂºÂ§n nhÃ†Â° bÃ¡ÂºÂ£o toÃƒÂ n khi bÃ¡Â»Â qua ma sÃƒÂ¡t.' }] },
  { key: 'cau truc chat', simulationType: 'nuclear-structure-3d', focus: 'DÃƒÂ¹ng mÃƒÂ´ hÃƒÂ¬nh vi mÃƒÂ´ Ã„â€˜Ã¡Â»Æ’ hÃƒÂ¬nh dung cÃ¡ÂºÂ¥u trÃƒÂºc hÃ¡ÂºÂ¡t vÃƒÂ  tÃ†Â°Ã†Â¡ng tÃƒÂ¡c trong chÃ¡ÂºÂ¥t.', components: [{ label: 'HÃ¡ÂºÂ¡t cÃ¡ÂºÂ¥u tÃ¡ÂºÂ¡o', note: 'CÃƒÂ¡c Ã„â€˜Ã†Â¡n vÃ¡Â»â€¹ vi mÃƒÂ´ biÃ¡Â»Æ’u diÃ¡Â»â€¦n nguyÃƒÂªn tÃ¡Â»Â­ hoÃ¡ÂºÂ·c phÃƒÂ¢n tÃ¡Â»Â­.' }, { label: 'LiÃƒÂªn kÃ¡ÂºÂ¿t lÃƒÂ¢n cÃ¡ÂºÂ­n', note: 'MÃƒÂ´ tÃ¡ÂºÂ£ tÃ†Â°Ã†Â¡ng tÃƒÂ¡c giÃ¡Â»Â¯ cÃƒÂ¡c hÃ¡ÂºÂ¡t Ã¡Â»Å¸ cÃ¡ÂºÂ¥u hÃƒÂ¬nh Ã¡Â»â€¢n Ã„â€˜Ã¡Â»â€¹nh.' }, { label: 'KhoÃ¡ÂºÂ£ng cÃƒÂ¡ch mÃ¡ÂºÂ¡ng', note: 'Cho thÃ¡ÂºÂ¥y chÃ¡ÂºÂ¥t rÃ¡ÂºÂ¯n, lÃ¡Â»Âng, khÃƒÂ­ khÃƒÂ¡c nhau Ã¡Â»Å¸ mÃ¡ÂºÂ­t Ã„â€˜Ã¡Â»â„¢ hÃ¡ÂºÂ¡t.' }] },
  { key: 'nhiet do va noi nang', simulationType: 'thermal-kinetic-3d', focus: 'NhÃƒÂ¬n mÃ¡Â»Â©c Ã„â€˜Ã¡Â»â„¢ chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng nhiÃ¡Â»â€¡t vÃƒÂ  nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng vi mÃƒÂ´ cÃ¡Â»Â§a phÃƒÂ¢n tÃ¡Â»Â­.', components: [{ label: 'PhÃƒÂ¢n tÃ¡Â»Â­ khÃƒÂ­', note: 'CÃƒÂ¡c hÃ¡ÂºÂ¡t chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng hÃ¡Â»â€”n loÃ¡ÂºÂ¡n Ã„â€˜Ã¡ÂºÂ¡i diÃ¡Â»â€¡n cho nÃ¡Â»â„¢i nÃ„Æ’ng vi mÃƒÂ´.' }, { label: 'NhiÃ¡Â»â€¡t Ã„â€˜Ã¡Â»â„¢ T', note: 'ChÃ¡Â»â€° mÃ¡Â»Â©c Ã„â€˜Ã¡Â»â„¢ chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng nhiÃ¡Â»â€¡t trung bÃƒÂ¬nh cÃ¡Â»Â§a cÃƒÂ¡c hÃ¡ÂºÂ¡t.' }, { label: 'BÃƒÂ¬nh chÃ¡Â»Â©a', note: 'KhÃƒÂ´ng gian Ã„â€˜Ã¡Â»Æ’ so sÃƒÂ¡nh trÃ¡ÂºÂ¡ng thÃƒÂ¡i khi tÃ„Æ’ng giÃ¡ÂºÂ£m nhiÃ¡Â»â€¡t.' }] },
  { key: 'qua trinh dang nhiet', simulationType: 'thermal-isothermal-3d', focus: 'Theo dÃƒÂµi khÃƒÂ­ biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i khi nhiÃ¡Â»â€¡t Ã„â€˜Ã¡Â»â„¢ giÃ¡Â»Â¯ khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.', components: [{ label: 'KhÃƒÂ­ trong xilanh', note: 'HÃ¡Â»â€¡ khÃ¡ÂºÂ£o sÃƒÂ¡t thay Ã„â€˜Ã¡Â»â€¢i ÃƒÂ¡p suÃ¡ÂºÂ¥t vÃƒÂ  thÃ¡Â»Æ’ tÃƒÂ­ch.' }, { label: 'Piston', note: 'BÃ¡Â»â„¢ phÃ¡ÂºÂ­n lÃƒÂ m thÃ¡Â»Æ’ tÃƒÂ­ch biÃ¡ÂºÂ¿n thiÃƒÂªn trong quÃƒÂ¡ trÃƒÂ¬nh Ã„â€˜Ã¡ÂºÂ³ng nhiÃ¡Â»â€¡t.' }, { label: 'NhiÃ¡Â»â€¡t kÃ¡ÂºÂ¿ chuÃ¡ÂºÂ©n', note: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh nhiÃ¡Â»â€¡t Ã„â€˜Ã¡Â»â„¢ Ã„â€˜Ã†Â°Ã¡Â»Â£c giÃ¡Â»Â¯ khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.' }] },
  { key: 'qua trinh dang ap', simulationType: 'thermal-isobaric-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh trÃ¡ÂºÂ¡ng thÃƒÂ¡i khÃƒÂ­ khi ÃƒÂ¡p suÃ¡ÂºÂ¥t khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i.', components: [{ label: 'KhÃƒÂ­ cÃƒÂ´ng tÃƒÂ¡c', note: 'MÃƒÂ´i chÃ¡ÂºÂ¥t Ã„â€˜Ã†Â°Ã¡Â»Â£c theo dÃƒÂµi trong bÃƒÂ¬nh hoÃ¡ÂºÂ·c xilanh.' }, { label: 'Piston tÃ¡Â»Â± do', note: 'Cho phÃƒÂ©p thÃ¡Â»Æ’ tÃƒÂ­ch thay Ã„â€˜Ã¡Â»â€¢i mÃƒÂ  ÃƒÂ¡p suÃ¡ÂºÂ¥t gÃ¡ÂºÂ§n nhÃ†Â° giÃ¡Â»Â¯ nguyÃƒÂªn.' }, { label: 'NguÃ¡Â»â€œn nhiÃ¡Â»â€¡t', note: 'TÃƒÂ¡c nhÃƒÂ¢n lÃƒÂ m nhiÃ¡Â»â€¡t Ã„â€˜Ã¡Â»â„¢ vÃƒÂ  thÃ¡Â»Æ’ tÃƒÂ­ch thay Ã„â€˜Ã¡Â»â€¢i.' }] },
  { key: 'phuong trinh trang thai', simulationType: 'thermal-state-equation-3d', focus: 'LiÃƒÂªn hÃ¡Â»â€¡ Ã„â€˜Ã¡Â»â€œng thÃ¡Â»Âi ba Ã„â€˜Ã¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng p, V vÃƒÂ  T.', components: [{ label: 'ÃƒÂp suÃ¡ÂºÂ¥t p', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng Ã„â€˜Ã¡ÂºÂ·c trÃ†Â°ng cho mÃ¡Â»Â©c va chÃ¡ÂºÂ¡m cÃ¡Â»Â§a phÃƒÂ¢n tÃ¡Â»Â­ lÃƒÂªn thÃƒÂ nh bÃƒÂ¬nh.' }, { label: 'ThÃ¡Â»Æ’ tÃƒÂ­ch V', note: 'KhÃƒÂ´ng gian chiÃ¡ÂºÂ¿m chÃ¡Â»â€” cÃ¡Â»Â§a khÃ¡Â»â€˜i khÃƒÂ­.' }, { label: 'NhiÃ¡Â»â€¡t Ã„â€˜Ã¡Â»â„¢ T', note: 'BiÃ¡ÂºÂ¿n trÃ¡ÂºÂ¡ng thÃƒÂ¡i phÃ¡ÂºÂ£n ÃƒÂ¡nh chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng nhiÃ¡Â»â€¡t trung bÃƒÂ¬nh.' }] },
  { key: 'bien dang co', simulationType: 'spring-3d', focus: 'Quan sÃƒÂ¡t kÃƒÂ©o nÃƒÂ©n vÃƒÂ  phÃ¡ÂºÂ£n Ã¡Â»Â©ng Ã„â€˜ÃƒÂ n hÃ¡Â»â€œi cÃ¡Â»Â§a vÃ¡ÂºÂ­t liÃ¡Â»â€¡u.', components: [{ label: 'MÃ¡ÂºÂ«u vÃ¡ÂºÂ­t', note: 'Ã„ÂoÃ¡ÂºÂ¡n vÃ¡ÂºÂ­t thÃ¡Â»Æ’ bÃ¡Â»â€¹ kÃƒÂ©o, nÃƒÂ©n hoÃ¡ÂºÂ·c uÃ¡Â»â€˜n trong mÃƒÂ´ phÃ¡Â»Âng.' }, { label: 'LÃ¡Â»Â±c tÃƒÂ¡c dÃ¡Â»Â¥ng', note: 'TÃƒÂ¡c nhÃƒÂ¢n gÃƒÂ¢y ra biÃ¡ÂºÂ¿n dÃ¡ÂºÂ¡ng cÃ†Â¡ hÃ¡Â»Âc.' }, { label: 'Ã„ÂÃ¡Â»â„¢ biÃ¡ÂºÂ¿n dÃ¡ÂºÂ¡ng', note: 'MÃ¡Â»Â©c thay Ã„â€˜Ã¡Â»â€¢i chiÃ¡Â»Âu dÃƒÂ i hoÃ¡ÂºÂ·c hÃƒÂ¬nh dÃ¡ÂºÂ¡ng cÃ¡Â»Â§a mÃ¡ÂºÂ«u.' }] },
  { key: 'suc cang be mat', simulationType: 'co-hoc-overview-visual', focus: 'MÃƒÂ´ tÃ¡ÂºÂ£ lÃ¡Â»Â±c liÃƒÂªn kÃ¡ÂºÂ¿t Ã¡Â»Å¸ mÃ¡ÂºÂ·t thoÃƒÂ¡ng chÃ¡ÂºÂ¥t lÃ¡Â»Âng.', components: [{ label: 'MÃ¡ÂºÂ·t thoÃƒÂ¡ng', note: 'BiÃƒÂªn phÃƒÂ¢n cÃƒÂ¡ch nÃ†Â¡i sÃ¡Â»Â©c cÃ„Æ’ng bÃ¡Â»Â mÃ¡ÂºÂ·t thÃ¡Â»Æ’ hiÃ¡Â»â€¡n rÃƒÂµ nhÃ¡ÂºÂ¥t.' }, { label: 'PhÃƒÂ¢n tÃ¡Â»Â­ bÃ¡Â»Â mÃ¡ÂºÂ·t', note: 'CÃƒÂ¡c hÃ¡ÂºÂ¡t chÃ¡Â»â€¹u lÃ¡Â»Â±c liÃƒÂªn kÃ¡ÂºÂ¿t khÃƒÂ´ng cÃƒÂ¢n bÃ¡ÂºÂ±ng Ã¡Â»Å¸ lÃ¡Â»â€ºp ngoÃƒÂ i cÃƒÂ¹ng.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng tiÃ¡ÂºÂ¿p xÃƒÂºc', note: 'VÃƒÂ¹ng xuÃ¡ÂºÂ¥t hiÃ¡Â»â€¡n lÃ¡Â»Â±c kÃƒÂ©o dÃ¡Â»Âc bÃ¡Â»Â mÃ¡ÂºÂ·t chÃ¡ÂºÂ¥t lÃ¡Â»Âng.' }] },
  { key: 'luc day archimedes', simulationType: 'co-hoc-overview-visual', focus: 'NhÃƒÂ¬n cÃƒÂ¢n bÃ¡ÂºÂ±ng giÃ¡Â»Â¯a trÃ¡Â»Âng lÃ†Â°Ã¡Â»Â£ng vÃƒÂ  lÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ©y chÃ¡ÂºÂ¥t lÃ†Â°u.', components: [{ label: 'VÃ¡ÂºÂ­t nhÃƒÂºng', note: 'Ã„ÂÃ¡Â»â€˜i tÃ†Â°Ã¡Â»Â£ng chÃ¡Â»â€¹u tÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â§a chÃ¡ÂºÂ¥t lÃ¡Â»Âng hoÃ¡ÂºÂ·c chÃ¡ÂºÂ¥t khÃƒÂ­.' }, { label: 'ChÃ¡ÂºÂ¥t lÃ†Â°u', note: 'MÃƒÂ´i trÃ†Â°Ã¡Â»Âng sinh ra lÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ©y hÃ†Â°Ã¡Â»â€ºng lÃƒÂªn.' }, { label: 'LÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ©y Archimedes', note: 'LÃ¡Â»Â±c do ÃƒÂ¡p suÃ¡ÂºÂ¥t chÃƒÂªnh lÃ¡Â»â€¡ch theo chiÃ¡Â»Âu sÃƒÂ¢u tÃ¡ÂºÂ¡o nÃƒÂªn.' }] },
  { key: 'su noi', simulationType: 'co-hoc-overview-visual', focus: 'Theo dÃƒÂµi Ã„â€˜iÃ¡Â»Âu kiÃ¡Â»â€¡n Ã„â€˜Ã¡Â»Æ’ vÃ¡ÂºÂ­t chÃƒÂ¬m, nÃ¡Â»â€¢i hoÃ¡ÂºÂ·c lÃ†Â¡ lÃ¡Â»Â­ng.', components: [{ label: 'VÃ¡ÂºÂ­t nÃ¡Â»â€¢i', note: 'Ã„ÂÃ¡Â»â€˜i tÃ†Â°Ã¡Â»Â£ng Ã„â€˜Ã†Â°Ã¡Â»Â£c so sÃƒÂ¡nh giÃ¡Â»Â¯a trÃ¡Â»Âng lÃ†Â°Ã¡Â»Â£ng vÃƒÂ  lÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ©y.' }, { label: 'MÃ¡Â»Â±c chÃ¡ÂºÂ¥t lÃ¡Â»Âng', note: 'Cho thÃ¡ÂºÂ¥y phÃ¡ÂºÂ§n thÃ¡Â»Æ’ tÃƒÂ­ch chÃƒÂ¬m khi vÃ¡ÂºÂ­t cÃƒÂ¢n bÃ¡ÂºÂ±ng.' }, { label: 'KhÃ¡Â»â€˜i lÃ†Â°Ã¡Â»Â£ng riÃƒÂªng', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh trÃ¡ÂºÂ¡ng thÃƒÂ¡i chÃƒÂ¬m nÃ¡Â»â€¢i cÃ¡Â»Â§a vÃ¡ÂºÂ­t.' }] },
  { key: 'dien tich', simulationType: 'coulomb-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh bÃ¡ÂºÂ£n chÃ¡ÂºÂ¥t Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch vÃƒÂ  tÃ†Â°Ã†Â¡ng tÃƒÂ¡c hÃƒÂºt Ã„â€˜Ã¡ÂºÂ©y.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n tÃƒÂ­ch q1', note: 'NguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch thÃ¡Â»Â© nhÃ¡ÂºÂ¥t trong mÃƒÂ´ hÃƒÂ¬nh.' }, { label: 'Ã„ÂiÃ¡Â»â€¡n tÃƒÂ­ch q2', note: 'NguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch thÃ¡Â»Â© hai Ã„â€˜Ã¡Â»Æ’ quan sÃƒÂ¡t tÃ†Â°Ã†Â¡ng tÃƒÂ¡c.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng nÃ¡Â»â€˜i hai Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch', note: 'PhÃ†Â°Ã†Â¡ng tÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â§a lÃ¡Â»Â±c Ã„â€˜iÃ¡Â»â€¡n tÃ„Â©nh.' }] },
  { key: 'dinh luat coulomb', simulationType: 'coulomb-3d', focus: 'NhÃƒÂ¬n rÃƒÂµ chiÃ¡Â»Âu lÃ¡Â»Â±c hÃƒÂºt Ã„â€˜Ã¡ÂºÂ©y vÃƒÂ  phÃ¡Â»Â¥ thuÃ¡Â»â„¢c theo khoÃ¡ÂºÂ£ng cÃƒÂ¡ch.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n tÃƒÂ­ch Ã„â€˜iÃ¡Â»Æ’m', note: 'Hai nguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch Ã„â€˜Ã†Â°Ã¡Â»Â£c xem nhÃ†Â° chÃ¡ÂºÂ¥t Ã„â€˜iÃ¡Â»Æ’m.' }, { label: 'KhoÃ¡ÂºÂ£ng cÃƒÂ¡ch r', note: 'BiÃ¡ÂºÂ¿n quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh Ã„â€˜Ã¡Â»â„¢ lÃ¡Â»â€ºn lÃ¡Â»Â±c theo quy luÃ¡ÂºÂ­t nghÃ¡Â»â€¹ch Ã„â€˜Ã¡ÂºÂ£o bÃƒÂ¬nh phÃ†Â°Ã†Â¡ng.' }, { label: 'VectÃ†Â¡ lÃ¡Â»Â±c Coulomb', note: 'ChÃ¡Â»â€° chiÃ¡Â»Âu vÃƒÂ  Ã„â€˜Ã¡Â»â„¢ mÃ¡ÂºÂ¡nh cÃ¡Â»Â§a tÃ†Â°Ã†Â¡ng tÃƒÂ¡c Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'dien truong deu', simulationType: 'electric-field-3d', focus: 'Quan sÃƒÂ¡t hÃ¡ÂºÂ¡t mang Ã„â€˜iÃ¡Â»â€¡n Ã„â€˜i giÃ¡Â»Â¯a hai bÃ¡ÂºÂ£n cÃ¡Â»Â±c.', components: [{ label: 'BÃ¡ÂºÂ£n dÃ†Â°Ã†Â¡ng', note: 'BÃ¡ÂºÂ£n cÃ¡Â»Â±c tÃ¡ÂºÂ¡o Ã„â€˜Ã¡ÂºÂ§u xuÃ¡ÂºÂ¥t phÃƒÂ¡t cÃ¡Â»Â§a Ã„â€˜Ã†Â°Ã¡Â»Âng sÃ¡Â»Â©c Ã„â€˜iÃ¡Â»â€¡n.' }, { label: 'BÃ¡ÂºÂ£n ÃƒÂ¢m', note: 'BÃ¡ÂºÂ£n cÃ¡Â»Â±c hÃƒÂºt cÃƒÂ¡c Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch dÃ†Â°Ã†Â¡ng theo chiÃ¡Â»Âu trÃ†Â°Ã¡Â»Âng.' }, { label: 'HÃ¡ÂºÂ¡t thÃ¡Â»Â­ q', note: 'VÃ¡ÂºÂ­t mang Ã„â€˜iÃ¡Â»â€¡n nhÃ¡Â»Â dÃƒÂ¹ng Ã„â€˜Ã¡Â»Æ’ Ã„â€˜Ã¡Â»Âc chiÃ¡Â»Âu lÃ¡Â»Â±c Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'cong cua luc dien', simulationType: 'electric-field-3d', focus: 'LiÃƒÂªn hÃ¡Â»â€¡ Ã„â€˜Ã¡Â»â„¢ dÃ¡Â»Âi trong Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng vÃ¡Â»â€ºi cÃƒÂ´ng cÃ¡Â»Â§a lÃ¡Â»Â±c Ã„â€˜iÃ¡Â»â€¡n.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n tÃƒÂ­ch di chuyÃ¡Â»Æ’n', note: 'HÃ¡ÂºÂ¡t khÃ¡ÂºÂ£o sÃƒÂ¡t nhÃ¡ÂºÂ­n cÃƒÂ´ng khi Ã„â€˜i trong Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng sÃ¡Â»Â©c Ã„â€˜iÃ¡Â»â€¡n', note: 'MÃ¡Â»â€˜c Ã„â€˜Ã¡Â»Æ’ xÃƒÂ¡c Ã„â€˜Ã¡Â»â€¹nh chiÃ¡Â»Âu dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n thuÃ¡ÂºÂ­n hay ngÃ†Â°Ã¡Â»Â£c trÃ†Â°Ã¡Â»Âng.' }, { label: 'Ã„ÂÃ¡Â»â„¢ dÃ¡Â»Âi hÃ¡Â»Â¯u hiÃ¡Â»â€¡u', note: 'PhÃ¡ÂºÂ§n dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n theo phÃ†Â°Ã†Â¡ng Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng sinh cÃƒÂ´ng.' }] },
  { key: 'dien the', simulationType: 'electric-field-3d', focus: 'NhÃƒÂ¬n Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿ nhÃ†Â° mÃ¡Â»Â©c nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡ÂºÂ¡i tÃ¡Â»Â«ng vÃƒÂ¹ng.', components: [{ label: 'MÃ¡ÂºÂ·t Ã„â€˜Ã¡ÂºÂ³ng thÃ¡ÂºÂ¿', note: 'TÃ¡ÂºÂ­p hÃ¡Â»Â£p cÃƒÂ¡c Ã„â€˜iÃ¡Â»Æ’m cÃƒÂ³ cÃƒÂ¹ng Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿.' }, { label: 'Ã„ÂiÃ¡Â»â€¡n tÃƒÂ­ch thÃ¡Â»Â­', note: 'GiÃƒÂºp hÃƒÂ¬nh dung khÃ¡ÂºÂ£ nÃ„Æ’ng sinh cÃƒÂ´ng cÃ¡Â»Â§a Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng.' }, { label: 'HiÃ¡Â»â€¡u Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿', note: 'Ã„ÂÃ¡Â»â„¢ chÃƒÂªnh Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿ giÃ¡Â»Â¯a hai vÃ¡Â»â€¹ trÃƒÂ­ quan sÃƒÂ¡t.' }] },
  { key: 'cuong do dong dien', simulationType: 'ohm-circuit-3d', focus: 'Cho thÃ¡ÂºÂ¥y dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n lÃƒÂ  tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch qua tiÃ¡ÂºÂ¿t diÃ¡Â»â€¡n.', components: [{ label: 'NguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n', note: 'ThiÃ¡ÂºÂ¿t bÃ¡Â»â€¹ tÃ¡ÂºÂ¡o ra sÃ¡Â»Â± chÃƒÂªnh lÃ¡Â»â€¡ch Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿ duy trÃƒÂ¬ dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n.' }, { label: 'DÃƒÂ¢y dÃ¡ÂºÂ«n', note: 'MÃƒÂ´i trÃ†Â°Ã¡Â»Âng Ã„â€˜Ã¡Â»Æ’ Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch dÃ¡Â»â€¹ch chuyÃ¡Â»Æ’n cÃƒÂ³ hÃ†Â°Ã¡Â»â€ºng.' }, { label: 'CÃ†Â°Ã¡Â»Âng Ã„â€˜Ã¡Â»â„¢ I', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng biÃ¡Â»Æ’u diÃ¡Â»â€¦n Ã„â€˜Ã¡Â»â„¢ mÃ¡ÂºÂ¡nh cÃ¡Â»Â§a dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'nguon dien', simulationType: 'ohm-circuit-3d', focus: 'NhÃ¡ÂºÂ¥n vai trÃƒÂ² cÃ¡Â»Â§a nguÃ¡Â»â€œn trong viÃ¡Â»â€¡c duy trÃƒÂ¬ hiÃ¡Â»â€¡u Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿.', components: [{ label: 'NguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n', note: 'BÃ¡Â»â„¢ phÃ¡ÂºÂ­n cung cÃ¡ÂºÂ¥p nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng cho mÃ¡ÂºÂ¡ch ngoÃƒÂ i.' }, { label: 'CÃ¡Â»Â±c nguÃ¡Â»â€œn', note: 'Hai Ã„â€˜Ã¡ÂºÂ§u cÃƒÂ³ sÃ¡Â»Â± chÃƒÂªnh lÃ¡Â»â€¡ch Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿.' }, { label: 'MÃ¡ÂºÂ¡ch ngoÃƒÂ i', note: 'PhÃ¡ÂºÂ§n tiÃƒÂªu thÃ¡Â»Â¥ nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng do nguÃ¡Â»â€œn cung cÃ¡ÂºÂ¥p.' }] },
  { key: 'dinh luat ohm', simulationType: 'ohm-circuit-3d', focus: 'LiÃƒÂªn hÃ¡Â»â€¡ U, I vÃƒÂ  R trÃ¡Â»Â±c tiÃ¡ÂºÂ¿p trÃƒÂªn mÃ¡ÂºÂ¡ch tÃ¡ÂºÂ£i.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n trÃ¡Â»Å¸ R', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ cÃ¡ÂºÂ£n trÃ¡Â»Å¸ dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n Ã„â€˜i qua.' }, { label: 'HiÃ¡Â»â€¡u Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿ U', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ Ã„â€˜Ã¡ÂºÂ©y dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n qua Ã„â€˜iÃ¡Â»â€¡n trÃ¡Â»Å¸.' }, { label: 'DÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n I', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng Ã„â€˜ÃƒÂ¡p Ã¡Â»Â©ng theo Ã„â€˜Ã¡Â»â€¹nh luÃ¡ÂºÂ­t Ohm.' }] },
  { key: 'cong suat dien', simulationType: 'ohm-circuit-3d', focus: 'NhÃƒÂ¬n tÃ¡ÂºÂ£i tiÃƒÂªu thÃ¡Â»Â¥ nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng Ã„â€˜iÃ¡Â»â€¡n theo thÃ¡Â»Âi gian.', components: [{ label: 'TÃ¡ÂºÂ£i tiÃƒÂªu thÃ¡Â»Â¥', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ nhÃ¡ÂºÂ­n Ã„â€˜iÃ¡Â»â€¡n nÃ„Æ’ng vÃƒÂ  biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i thÃƒÂ nh dÃ¡ÂºÂ¡ng nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng khÃƒÂ¡c.' }, { label: 'DÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n chÃ¡ÂºÂ¡y qua tÃ¡ÂºÂ£i', note: 'YÃ¡ÂºÂ¿u tÃ¡Â»â€˜ quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh cÃƒÂ´ng suÃ¡ÂºÂ¥t cÃƒÂ¹ng vÃ¡Â»â€ºi hiÃ¡Â»â€¡u Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿.' }, { label: 'Ã„ÂÃ¡Â»â„¢ sÃƒÂ¡ng/hiÃ¡Â»â€¡u Ã¡Â»Â©ng nhiÃ¡Â»â€¡t', note: 'BiÃ¡Â»Æ’u hiÃ¡Â»â€¡n trÃ¡Â»Â±c quan cÃ¡Â»Â§a cÃƒÂ´ng suÃ¡ÂºÂ¥t Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'mach dien hon hop', simulationType: 'ohm-circuit-3d', focus: 'So sÃƒÂ¡nh nhanh cÃƒÂ¡c nhÃƒÂ¡nh nÃ¡Â»â€˜i tiÃ¡ÂºÂ¿p vÃƒÂ  song song.', components: [{ label: 'NhÃƒÂ¡nh nÃ¡Â»â€˜i tiÃ¡ÂºÂ¿p', note: 'PhÃ¡ÂºÂ§n mÃ¡ÂºÂ¡ch cÃƒÂ³ cÃƒÂ¹ng dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n chÃ¡ÂºÂ¡y qua.' }, { label: 'NhÃƒÂ¡nh song song', note: 'PhÃ¡ÂºÂ§n mÃ¡ÂºÂ¡ch cÃƒÂ³ cÃƒÂ¹ng hiÃ¡Â»â€¡u Ã„â€˜iÃ¡Â»â€¡n thÃ¡ÂºÂ¿ Ã¡Â»Å¸ hai Ã„â€˜Ã¡ÂºÂ§u.' }, { label: 'NÃƒÂºt mÃ¡ÂºÂ¡ch', note: 'Ã„ÂiÃ¡Â»Æ’m phÃƒÂ¢n chia hoÃ¡ÂºÂ·c hÃ¡Â»â„¢i tÃ¡Â»Â¥ cÃ¡Â»Â§a nhiÃ¡Â»Âu nhÃƒÂ¡nh Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'cam ung tu', simulationType: 'magnetic-field-lines-3d', focus: 'Quan sÃƒÂ¡t hÃƒÂ¬nh dÃ¡ÂºÂ¡ng vÃƒÂ  chiÃ¡Â»Âu cÃ¡Â»Â§a Ã„â€˜Ã†Â°Ã¡Â»Âng sÃ¡Â»Â©c tÃ¡Â»Â«.', components: [{ label: 'NguÃ¡Â»â€œn tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng', note: 'Nam chÃƒÂ¢m hoÃ¡ÂºÂ·c dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n sinh ra cÃ¡ÂºÂ£m Ã¡Â»Â©ng tÃ¡Â»Â«.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng sÃ¡Â»Â©c tÃ¡Â»Â«', note: 'Ã„ÂÃ†Â°Ã¡Â»Âng mÃƒÂ´ tÃ¡ÂºÂ£ hÃ†Â°Ã¡Â»â€ºng cÃ¡Â»Â§a vectÃ†Â¡ cÃ¡ÂºÂ£m Ã¡Â»Â©ng tÃ¡Â»Â« B.' }, { label: 'Kim thÃ¡Â»Â­', note: 'ThÃƒÂ nh phÃ¡ÂºÂ§n nhÃ¡Â»Â dÃƒÂ¹ng Ã„â€˜Ã¡Â»Æ’ nhÃ¡ÂºÂ­n biÃ¡ÂºÂ¿t chiÃ¡Â»Âu tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng.' }] },
  { key: 'luc lorentz', simulationType: 'magnetic-helix-3d', focus: 'Theo dÃƒÂµi quÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o hÃ¡ÂºÂ¡t Ã„â€˜iÃ¡Â»â€¡n tÃƒÂ­ch trong tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng Ã„â€˜Ã¡Â»Âu.', components: [{ label: 'HÃ¡ÂºÂ¡t tÃƒÂ­ch Ã„â€˜iÃ¡Â»â€¡n', note: 'Ã„ÂÃ¡Â»â€˜i tÃ†Â°Ã¡Â»Â£ng chÃ¡Â»â€¹u tÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â§a lÃ¡Â»Â±c Lorentz.' }, { label: 'TÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng B', note: 'TrÃ†Â°Ã¡Â»Âng Ã„â€˜Ã¡Â»Âu Ã„â€˜ÃƒÂ³ng vai trÃƒÂ² nÃ¡Â»Ân cho chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'QuÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o xoÃ¡ÂºÂ¯n Ã¡Â»â€˜c', note: 'KÃ¡ÂºÂ¿t quÃ¡ÂºÂ£ khi hÃ¡ÂºÂ¡t vÃ¡Â»Â«a cÃƒÂ³ vÃ¡ÂºÂ­n tÃ¡Â»â€˜c vuÃƒÂ´ng gÃƒÂ³c vÃ¡Â»Â«a song song vÃ¡Â»â€ºi B.' }] },
  { key: 'luc tu tac dung len day dan', simulationType: 'magnetic-field-lines-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh chiÃ¡Â»Âu lÃ¡Â»Â±c tÃ¡Â»Â« theo quy tÃ¡ÂºÂ¯c bÃƒÂ n tay.', components: [{ label: 'DÃƒÂ¢y dÃ¡ÂºÂ«n mang dÃƒÂ²ng', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ chÃ¡Â»â€¹u lÃ¡Â»Â±c khi Ã„â€˜Ã¡ÂºÂ·t trong tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng.' }, { label: 'TÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng ngoÃƒÂ i', note: 'TrÃ†Â°Ã¡Â»Âng tÃ†Â°Ã†Â¡ng tÃƒÂ¡c vÃ¡Â»â€ºi dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n trong dÃƒÂ¢y.' }, { label: 'LÃ¡Â»Â±c tÃ¡Â»Â«', note: 'LÃ¡Â»Â±c lÃƒÂ m dÃƒÂ¢y lÃ¡Â»â€¡ch hoÃ¡ÂºÂ·c chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng trong mÃƒÂ´ phÃ¡Â»Âng.' }] },
  { key: 'tu thong', simulationType: 'induction-3d', focus: 'NhÃƒÂ¬n lÃ†Â°Ã¡Â»Â£ng Ã„â€˜Ã†Â°Ã¡Â»Âng sÃ¡Â»Â©c xuyÃƒÂªn qua tiÃ¡ÂºÂ¿t diÃ¡Â»â€¡n mÃ¡ÂºÂ¡ch.', components: [{ label: 'Khung dÃƒÂ¢y', note: 'DiÃ¡Â»â€¡n tÃƒÂ­ch nhÃ¡ÂºÂ­n tÃ¡Â»Â« thÃƒÂ´ng Ã„â€˜i qua.' }, { label: 'VectÃ†Â¡ phÃƒÂ¡p tuyÃ¡ÂºÂ¿n', note: 'DÃƒÂ¹ng Ã„â€˜Ã¡Â»Æ’ xÃƒÂ¡c Ã„â€˜Ã¡Â»â€¹nh gÃƒÂ³c vÃ¡Â»â€ºi tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng.' }, { label: 'TÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng B', note: 'NguÃ¡Â»â€œn Ã„â€˜Ã†Â°Ã¡Â»Âng sÃ¡Â»Â©c tÃ¡Â»Â« xuyÃƒÂªn qua khung.' }] },
  { key: 'hien tuong cam ung dien tu', simulationType: 'induction-3d', focus: 'ThÃ¡ÂºÂ¥y rÃƒÂµ tÃ¡Â»Â« thÃƒÂ´ng biÃ¡ÂºÂ¿n thiÃƒÂªn sinh suÃ¡ÂºÂ¥t Ã„â€˜iÃ¡Â»â€¡n Ã„â€˜Ã¡Â»â„¢ng cÃ¡ÂºÂ£m Ã¡Â»Â©ng.', components: [{ label: 'CuÃ¡Â»â„¢n dÃƒÂ¢y', note: 'NÃ†Â¡i xuÃ¡ÂºÂ¥t hiÃ¡Â»â€¡n suÃ¡ÂºÂ¥t Ã„â€˜iÃ¡Â»â€¡n Ã„â€˜Ã¡Â»â„¢ng cÃ¡ÂºÂ£m Ã¡Â»Â©ng.' }, { label: 'Nam chÃƒÂ¢m chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng', note: 'TÃƒÂ¡c nhÃƒÂ¢n lÃƒÂ m tÃ¡Â»Â« thÃƒÂ´ng qua cuÃ¡Â»â„¢n biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i.' }, { label: 'Kim Ã„â€˜o dÃƒÂ²ng', note: 'BÃ¡Â»â„¢ phÃ¡ÂºÂ­n cho biÃ¡ÂºÂ¿t dÃƒÂ²ng cÃ¡ÂºÂ£m Ã¡Â»Â©ng xuÃ¡ÂºÂ¥t hiÃ¡Â»â€¡n vÃƒÂ  Ã„â€˜Ã¡Â»â€¢i chiÃ¡Â»Âu.' }] },
  { key: 'khuc xa anh sang', simulationType: 'refraction-3d', focus: 'Ã„ÂÃ¡Â»Âc tia tÃ¡Â»â€ºi, phÃƒÂ¡p tuyÃ¡ÂºÂ¿n vÃƒÂ  tia khÃƒÂºc xÃ¡ÂºÂ¡ thÃ¡ÂºÂ­t trÃ¡Â»Â±c quan.', components: [{ label: 'Tia tÃ¡Â»â€ºi', note: 'ChÃƒÂ¹m sÃƒÂ¡ng Ã„â€˜i tÃ¡Â»â€ºi mÃ¡ÂºÂ·t phÃƒÂ¢n cÃƒÂ¡ch giÃ¡Â»Â¯a hai mÃƒÂ´i trÃ†Â°Ã¡Â»Âng.' }, { label: 'PhÃƒÂ¡p tuyÃ¡ÂºÂ¿n', note: 'Ã„ÂÃ†Â°Ã¡Â»Âng chuÃ¡ÂºÂ©n Ã„â€˜Ã¡Â»Æ’ Ã„â€˜o gÃƒÂ³c tÃ¡Â»â€ºi vÃƒÂ  gÃƒÂ³c khÃƒÂºc xÃ¡ÂºÂ¡.' }, { label: 'Tia khÃƒÂºc xÃ¡ÂºÂ¡', note: 'ChÃƒÂ¹m sÃƒÂ¡ng bÃ¡Â»â€¹ Ã„â€˜Ã¡Â»â€¢i hÃ†Â°Ã¡Â»â€ºng khi Ã„â€˜i vÃƒÂ o mÃƒÂ´i trÃ†Â°Ã¡Â»Âng mÃ¡Â»â€ºi.' }] },
  { key: 'phan xa toan phan', simulationType: 'refraction-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh Ã„â€˜iÃ¡Â»Âu kiÃ¡Â»â€¡n gÃƒÂ³c giÃ¡Â»â€ºi hÃ¡ÂºÂ¡n vÃƒÂ  tia phÃ¡ÂºÂ£n xÃ¡ÂºÂ¡ toÃƒÂ n phÃ¡ÂºÂ§n.', components: [{ label: 'MÃƒÂ´i trÃ†Â°Ã¡Â»Âng chiÃ¡ÂºÂ¿t suÃ¡ÂºÂ¥t lÃ¡Â»â€ºn', note: 'NÃ†Â¡i tia sÃƒÂ¡ng truyÃ¡Â»Ân trÃ†Â°Ã¡Â»â€ºc khi gÃ¡ÂºÂ·p mÃ¡ÂºÂ·t phÃƒÂ¢n cÃƒÂ¡ch.' }, { label: 'GÃƒÂ³c tÃ¡Â»â€ºi i', note: 'BiÃ¡ÂºÂ¿n Ã„â€˜iÃ¡Â»Âu khiÃ¡Â»Æ’n viÃ¡Â»â€¡c cÃƒÂ³ xÃ¡ÂºÂ£y ra phÃ¡ÂºÂ£n xÃ¡ÂºÂ¡ toÃƒÂ n phÃ¡ÂºÂ§n hay khÃƒÂ´ng.' }, { label: 'Tia phÃ¡ÂºÂ£n xÃ¡ÂºÂ¡ toÃƒÂ n phÃ¡ÂºÂ§n', note: 'Tia bÃ¡Â»â€¹ giÃ¡Â»Â¯ lÃ¡ÂºÂ¡i hoÃƒÂ n toÃƒÂ n trong mÃƒÂ´i trÃ†Â°Ã¡Â»Âng Ã„â€˜Ã¡ÂºÂ§u.' }] },
  { key: 'thau kinh mong', simulationType: 'lens-3d', focus: 'VÃ¡ÂºÂ½ tia Ã„â€˜Ã¡ÂºÂ·c biÃ¡Â»â€¡t vÃƒÂ  vÃ¡Â»â€¹ trÃƒÂ­ Ã¡ÂºÂ£nh theo khoÃ¡ÂºÂ£ng cÃƒÂ¡ch vÃ¡ÂºÂ­t.', components: [{ label: 'ThÃ¡ÂºÂ¥u kÃƒÂ­nh', note: 'BÃ¡Â»â„¢ phÃ¡ÂºÂ­n quang hÃ¡Â»Âc lÃƒÂ m hÃ¡Â»â„¢i tÃ¡Â»Â¥ hoÃ¡ÂºÂ·c phÃƒÂ¢n kÃƒÂ¬ chÃƒÂ¹m tia.' }, { label: 'VÃ¡ÂºÂ­t sÃƒÂ¡ng', note: 'NguÃ¡Â»â€œn phÃƒÂ¡t tia Ã„â€˜Ã¡Â»Æ’ dÃ¡Â»Â±ng Ã¡ÂºÂ£nh qua thÃ¡ÂºÂ¥u kÃƒÂ­nh.' }, { label: 'MÃƒÂ n Ã¡ÂºÂ£nh / vÃ¡Â»â€¹ trÃƒÂ­ Ã¡ÂºÂ£nh', note: 'NÃ†Â¡i quan sÃƒÂ¡t Ã¡ÂºÂ£nh thÃ¡ÂºÂ­t hoÃ¡ÂºÂ·c Ã¡ÂºÂ£o hÃƒÂ¬nh thÃƒÂ nh.' }] },
  { key: 'mat va cac tat cua mat', simulationType: 'eye-optics-3d', focus: 'Theo dÃƒÂµi Ã„â€˜iÃ¡Â»Æ’m hÃ¡Â»â„¢i tÃ¡Â»Â¥ so vÃ¡Â»â€ºi vÃƒÂµng mÃ¡ÂºÂ¡c Ã„â€˜Ã¡Â»Æ’ phÃƒÂ¢n biÃ¡Â»â€¡t tÃ¡ÂºÂ­t mÃ¡ÂºÂ¯t.', components: [{ label: 'ThÃ¡Â»Â§y tinh thÃ¡Â»Æ’', note: 'ThÃƒÂ nh phÃ¡ÂºÂ§n Ã„â€˜iÃ¡Â»Âu tiÃ¡ÂºÂ¿t tiÃƒÂªu cÃ¡Â»Â± cÃ¡Â»Â§a mÃ¡ÂºÂ¯t.' }, { label: 'VÃƒÂµng mÃ¡ÂºÂ¡c', note: 'MÃ¡ÂºÂ·t thu Ã¡ÂºÂ£nh rÃƒÂµ khi chÃƒÂ¹m tia hÃ¡Â»â„¢i tÃ¡Â»Â¥ Ã„â€˜ÃƒÂºng vÃ¡Â»â€¹ trÃƒÂ­.' }, { label: 'Ã„ÂiÃ¡Â»Æ’m hÃ¡Â»â„¢i tÃ¡Â»Â¥', note: 'Cho biÃ¡ÂºÂ¿t mÃ¡ÂºÂ¯t Ã„â€˜ang bÃƒÂ¬nh thÃ†Â°Ã¡Â»Âng, cÃ¡ÂºÂ­n hay viÃ¡Â»â€¦n.' }] },
  { key: 'kinh lup kinh hien vi kinh thien van', simulationType: 'microscope-3d', focus: 'So sÃƒÂ¡nh vai trÃƒÂ² cÃ¡Â»Â§a vÃ¡ÂºÂ­t kÃƒÂ­nh vÃƒÂ  thÃ¡Â»â€¹ kÃƒÂ­nh trong cÃƒÂ¡c dÃ¡Â»Â¥ng cÃ¡Â»Â¥ quang.', components: [{ label: 'VÃ¡ÂºÂ­t kÃƒÂ­nh', note: 'ThÃ¡ÂºÂ¥u kÃƒÂ­nh Ã„â€˜Ã¡ÂºÂ§u tiÃƒÂªn tÃ¡ÂºÂ¡o Ã¡ÂºÂ£nh trung gian.' }, { label: 'ThÃ¡Â»â€¹ kÃƒÂ­nh', note: 'ThÃ¡ÂºÂ¥u kÃƒÂ­nh thÃ¡Â»Â© hai dÃƒÂ¹ng Ã„â€˜Ã¡Â»Æ’ phÃƒÂ³ng Ã„â€˜Ã¡ÂºÂ¡i Ã¡ÂºÂ£nh trung gian.' }, { label: 'Ã¡ÂºÂ¢nh quan sÃƒÂ¡t', note: 'KÃ¡ÂºÂ¿t quÃ¡ÂºÂ£ cuÃ¡Â»â€˜i cÃƒÂ¹ng ngÃ†Â°Ã¡Â»Âi hÃ¡Â»Âc cÃ¡ÂºÂ§n Ã„â€˜Ã¡Â»Âc vÃ¡Â»Â Ã„â€˜Ã¡Â»â„¢ lÃ¡Â»â€ºn vÃƒÂ  tÃƒÂ­nh chÃ¡ÂºÂ¥t Ã¡ÂºÂ£nh.' }] },
  { key: 'dao dong dieu hoa', simulationType: 'spring-3d', focus: 'Theo dÃƒÂµi li Ã„â€˜Ã¡Â»â„¢, vÃ¡ÂºÂ­n tÃ¡Â»â€˜c vÃƒÂ  gia tÃ¡Â»â€˜c nhÃ†Â° ba Ã„â€˜Ã¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng lÃ¡Â»â€¡ch pha.', components: [{ label: 'VÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng', note: 'KhÃ¡Â»â€˜i lÃ†Â°Ã¡Â»Â£ng chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng qua lÃ¡ÂºÂ¡i quanh vÃ¡Â»â€¹ trÃƒÂ­ cÃƒÂ¢n bÃ¡ÂºÂ±ng.' }, { label: 'Li Ã„â€˜Ã¡Â»â„¢ x', note: 'Ã„ÂÃ¡Â»â„¢ lÃ¡Â»â€¡ch tÃ¡Â»Â©c thÃ¡Â»Âi cÃ¡Â»Â§a vÃ¡ÂºÂ­t so vÃ¡Â»â€ºi vÃ¡Â»â€¹ trÃƒÂ­ cÃƒÂ¢n bÃ¡ÂºÂ±ng.' }, { label: 'Chu kÃƒÂ¬ T', note: 'KhoÃ¡ÂºÂ£ng thÃ¡Â»Âi gian Ã„â€˜Ã¡Â»Æ’ trÃ¡ÂºÂ¡ng thÃƒÂ¡i dao Ã„â€˜Ã¡Â»â„¢ng lÃ¡ÂºÂ·p lÃ¡ÂºÂ¡i.' }] },
  { key: 'con lac lo xo', simulationType: 'spring-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh lÃ¡Â»Â±c kÃƒÂ©o vÃ¡Â»Â vÃƒÂ  chu kÃƒÂ¬ theo k, m.', components: [{ label: 'LÃƒÂ² xo', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ tÃ¡ÂºÂ¡o lÃ¡Â»Â±c Ã„â€˜ÃƒÂ n hÃ¡Â»â€œi lÃƒÂ m vÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'KhÃ¡Â»â€˜i lÃ†Â°Ã¡Â»Â£ng m', note: 'VÃ¡ÂºÂ­t nÃ¡ÂºÂ·ng quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh quÃƒÂ¡n tÃƒÂ­nh cÃ¡Â»Â§a hÃ¡Â»â€¡.' }, { label: 'VÃ¡Â»â€¹ trÃƒÂ­ cÃƒÂ¢n bÃ¡ÂºÂ±ng', note: 'MÃ¡Â»â€˜c trung tÃƒÂ¢m quanh Ã„â€˜ÃƒÂ³ vÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng.' }] },
  { key: 'con lac don', simulationType: 'pendulum-3d', focus: 'Ã„ÂÃ¡Â»Âc biÃƒÂªn gÃƒÂ³c, dÃƒÂ¢y treo vÃƒÂ  quÃƒÂ£ng chuyÃ¡Â»Æ’n Ã„â€˜Ã¡Â»â„¢ng trÃƒÂªn cung trÃƒÂ²n.', components: [{ label: 'DÃƒÂ¢y treo', note: 'ChiÃ¡Â»Âu dÃƒÂ i dÃƒÂ¢y quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh chu kÃƒÂ¬ dao Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'QuÃ¡ÂºÂ£ nÃ¡ÂºÂ·ng', note: 'VÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng quanh vÃ¡Â»â€¹ trÃƒÂ­ thÃ¡ÂºÂ¥p nhÃ¡ÂºÂ¥t.' }, { label: 'GÃƒÂ³c lÃ¡Â»â€¡ch', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng mÃƒÂ´ tÃ¡ÂºÂ£ biÃƒÂªn Ã„â€˜Ã¡Â»â„¢ gÃƒÂ³c cÃ¡Â»Â§a con lÃ¡ÂºÂ¯c Ã„â€˜Ã†Â¡n.' }] },
  { key: 'nang luong dao dong', simulationType: 'pendulum-3d', focus: 'Quan sÃƒÂ¡t luÃƒÂ¢n phiÃƒÂªn giÃ¡Â»Â¯a Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng vÃƒÂ  thÃ¡ÂºÂ¿ nÃ„Æ’ng.', components: [{ label: 'BiÃƒÂªn dao Ã„â€˜Ã¡Â»â„¢ng', note: 'VÃ¡Â»â€¹ trÃƒÂ­ thÃ¡ÂºÂ¿ nÃ„Æ’ng lÃ¡Â»â€ºn nhÃ¡ÂºÂ¥t, vÃ¡ÂºÂ­n tÃ¡Â»â€˜c bÃ¡ÂºÂ±ng khÃƒÂ´ng.' }, { label: 'VÃ¡Â»â€¹ trÃƒÂ­ cÃƒÂ¢n bÃ¡ÂºÂ±ng', note: 'NÃ†Â¡i Ã„â€˜Ã¡Â»â„¢ng nÃ„Æ’ng lÃ¡Â»â€ºn nhÃ¡ÂºÂ¥t trong chu kÃƒÂ¬.' }, { label: 'TÃ¡Â»â€¢ng nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng gÃ¡ÂºÂ§n nhÃ†Â° khÃƒÂ´ng Ã„â€˜Ã¡Â»â€¢i nÃ¡ÂºÂ¿u bÃ¡Â»Â qua lÃ¡Â»Â±c cÃ¡ÂºÂ£n.' }] },
  { key: 'tong hop dao dong', simulationType: 'wave-3d', focus: 'HiÃ¡Â»Æ’u tÃ¡Â»â€¢ng hÃ¡Â»Â£p dao Ã„â€˜Ã¡Â»â„¢ng nhÃ†Â° cÃ¡Â»â„¢ng vectÃ†Â¡ pha.', components: [{ label: 'Dao Ã„â€˜Ã¡Â»â„¢ng thÃƒÂ nh phÃ¡ÂºÂ§n 1', note: 'NguÃ¡Â»â€œn dao Ã„â€˜Ã¡Â»â„¢ng thÃ¡Â»Â© nhÃ¡ÂºÂ¥t gÃƒÂ³p phÃ¡ÂºÂ§n tÃ¡ÂºÂ¡o dao Ã„â€˜Ã¡Â»â„¢ng tÃ¡Â»â€¢ng.' }, { label: 'Dao Ã„â€˜Ã¡Â»â„¢ng thÃƒÂ nh phÃ¡ÂºÂ§n 2', note: 'NguÃ¡Â»â€œn dao Ã„â€˜Ã¡Â»â„¢ng thÃ¡Â»Â© hai cÃƒÂ¹ng phÃ†Â°Ã†Â¡ng cÃƒÂ¹ng tÃ¡ÂºÂ§n sÃ¡Â»â€˜.' }, { label: 'Dao Ã„â€˜Ã¡Â»â„¢ng tÃ¡Â»â€¢ng hÃ¡Â»Â£p', note: 'KÃ¡ÂºÂ¿t quÃ¡ÂºÂ£ cÃ¡Â»â„¢ng biÃƒÂªn Ã„â€˜Ã¡Â»â„¢ vÃƒÂ  pha cÃ¡Â»Â§a cÃƒÂ¡c dao Ã„â€˜Ã¡Â»â„¢ng thÃƒÂ nh phÃ¡ÂºÂ§n.' }] },
  { key: 'dai cuong ve song', simulationType: 'wave-3d', focus: 'Theo dÃƒÂµi biÃƒÂªn Ã„â€˜Ã¡Â»â„¢, bÃ†Â°Ã¡Â»â€ºc sÃƒÂ³ng vÃƒÂ  tÃ¡Â»â€˜c Ã„â€˜Ã¡Â»â„¢ truyÃ¡Â»Ân pha.', components: [{ label: 'NguÃ¡Â»â€œn sÃƒÂ³ng', note: 'Ã„ÂiÃ¡Â»Æ’m phÃƒÂ¡t dao Ã„â€˜Ã¡Â»â„¢ng ban Ã„â€˜Ã¡ÂºÂ§u cho mÃƒÂ´i trÃ†Â°Ã¡Â»Âng.' }, { label: 'MÃ¡ÂºÂ·t sÃƒÂ³ng / dÃƒÂ¢y sÃƒÂ³ng', note: 'PhÃ¡ÂºÂ§n mÃƒÂ´i trÃ†Â°Ã¡Â»Âng truyÃ¡Â»Ân trÃ¡ÂºÂ¡ng thÃƒÂ¡i dao Ã„â€˜Ã¡Â»â„¢ng.' }, { label: 'BÃ†Â°Ã¡Â»â€ºc sÃƒÂ³ng ÃŽÂ»', note: 'KhoÃ¡ÂºÂ£ng cÃƒÂ¡ch giÃ¡Â»Â¯a hai Ã„â€˜iÃ¡Â»Æ’m gÃ¡ÂºÂ§n nhau dao Ã„â€˜Ã¡Â»â„¢ng cÃƒÂ¹ng pha.' }] },
  { key: 'giao thoa song', simulationType: 'interference-3d', focus: 'ThÃ¡ÂºÂ¥y rÃƒÂµ vÃƒÂ¹ng cÃ¡Â»Â±c Ã„â€˜Ã¡ÂºÂ¡i vÃƒÂ  cÃ¡Â»Â±c tiÃ¡Â»Æ’u giao thoa.', components: [{ label: 'NguÃ¡Â»â€œn S1', note: 'NguÃ¡Â»â€œn phÃƒÂ¡t sÃƒÂ³ng kÃ¡ÂºÂ¿t hÃ¡Â»Â£p thÃ¡Â»Â© nhÃ¡ÂºÂ¥t.' }, { label: 'NguÃ¡Â»â€œn S2', note: 'NguÃ¡Â»â€œn phÃƒÂ¡t sÃƒÂ³ng kÃ¡ÂºÂ¿t hÃ¡Â»Â£p thÃ¡Â»Â© hai.' }, { label: 'VÃƒÂ¢n giao thoa', note: 'MiÃ¡Â»Ân khÃƒÂ´ng gian nÃ†Â¡i biÃƒÂªn Ã„â€˜Ã¡Â»â„¢ tÃ„Æ’ng cÃ†Â°Ã¡Â»Âng hoÃ¡ÂºÂ·c triÃ¡Â»â€¡t tiÃƒÂªu.' }] },
  { key: 'song dung', simulationType: 'standing-wave-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh vÃ¡Â»â€¹ trÃƒÂ­ nÃƒÂºt vÃƒÂ  bÃ¡Â»Â¥ng sÃƒÂ³ng cÃ¡Â»â€˜ Ã„â€˜Ã¡Â»â€¹nh.', components: [{ label: 'NÃƒÂºt sÃƒÂ³ng', note: 'Ã„ÂiÃ¡Â»Æ’m luÃƒÂ´n Ã„â€˜Ã¡Â»Â©ng yÃƒÂªn trong mÃƒÂ´ hÃƒÂ¬nh sÃƒÂ³ng dÃ¡Â»Â«ng.' }, { label: 'BÃ¡Â»Â¥ng sÃƒÂ³ng', note: 'Ã„ÂiÃ¡Â»Æ’m dao Ã„â€˜Ã¡Â»â„¢ng vÃ¡Â»â€ºi biÃƒÂªn Ã„â€˜Ã¡Â»â„¢ lÃ¡Â»â€ºn nhÃ¡ÂºÂ¥t.' }, { label: 'ChiÃ¡Â»Âu dÃƒÂ i hÃ¡Â»Â¯u hiÃ¡Â»â€¡u', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh sÃ¡Â»â€˜ bÃƒÂ³ sÃƒÂ³ng trÃƒÂªn dÃƒÂ¢y.' }] },
  { key: 'am hoc', simulationType: 'wave-3d', focus: 'BiÃ¡Â»Æ’u diÃ¡Â»â€¦n sÃƒÂ³ng ÃƒÂ¢m nhÃ†Â° sÃƒÂ³ng cÃ†Â¡ dÃ¡Â»Âc lan truyÃ¡Â»Ân trong mÃƒÂ´i trÃ†Â°Ã¡Â»Âng.', components: [{ label: 'NguÃ¡Â»â€œn ÃƒÂ¢m', note: 'VÃ¡ÂºÂ­t dao Ã„â€˜Ã¡Â»â„¢ng phÃƒÂ¡t ra sÃƒÂ³ng ÃƒÂ¢m.' }, { label: 'VÃƒÂ¹ng nÃƒÂ©n vÃƒÂ  giÃƒÂ£n', note: 'Ã„ÂÃ¡ÂºÂ·c trÃ†Â°ng cÃ¡Â»Â§a sÃƒÂ³ng ÃƒÂ¢m truyÃ¡Â»Ân trong mÃƒÂ´i trÃ†Â°Ã¡Â»Âng vÃ¡ÂºÂ­t chÃ¡ÂºÂ¥t.' }, { label: 'TÃ¡ÂºÂ§n sÃ¡Â»â€˜ ÃƒÂ¢m', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ liÃƒÂªn hÃ¡Â»â€¡ trÃ¡Â»Â±c tiÃ¡ÂºÂ¿p vÃ¡Â»â€ºi Ã„â€˜Ã¡Â»â„¢ cao cÃ¡Â»Â§a ÃƒÂ¢m.' }] },
  { key: 'dong dien xoay chieu', simulationType: 'rlc-3d', focus: 'Quan sÃƒÂ¡t Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p vÃƒÂ  dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n biÃ¡ÂºÂ¿n thiÃƒÂªn Ã„â€˜iÃ¡Â»Âu hÃƒÂ²a theo thÃ¡Â»Âi gian.', components: [{ label: 'NguÃ¡Â»â€œn AC', note: 'NguÃ¡Â»â€œn Ã„â€˜iÃ¡Â»â€¡n tÃ¡ÂºÂ¡o ra Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p Ã„â€˜Ã¡Â»â€¢i chiÃ¡Â»Âu tuÃ¡ÂºÂ§n hoÃƒÂ n.' }, { label: 'DÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡Â»Â©c thÃ¡Â»Âi', note: 'Ã„ÂÃ¡ÂºÂ¡i lÃ†Â°Ã¡Â»Â£ng thay Ã„â€˜Ã¡Â»â€¢i theo thÃ¡Â»Âi gian cÃƒÂ¹ng hoÃ¡ÂºÂ·c lÃ¡Â»â€¡ch pha vÃ¡Â»â€ºi Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p.' }, { label: 'Ã„ÂÃ¡Â»â€œ thÃ¡Â»â€¹ sin', note: 'BiÃ¡Â»Æ’u diÃ¡Â»â€¦n dÃ¡ÂºÂ¡ng dao Ã„â€˜Ã¡Â»â„¢ng cÃ¡Â»Â§a U vÃƒÂ  I.' }] },
  { key: 'mach rlc', simulationType: 'rlc-3d', focus: 'Theo dÃƒÂµi tÃ¡Â»Â«ng phÃ¡ÂºÂ§n tÃ¡Â»Â­ R, L, C vÃƒÂ  trÃ¡ÂºÂ¡ng thÃƒÂ¡i cÃ¡Â»â„¢ng hÃ†Â°Ã¡Â»Å¸ng.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n trÃ¡Â»Å¸ R', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ tiÃƒÂªu tÃƒÂ¡n nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng trong mÃ¡ÂºÂ¡ch.' }, { label: 'CuÃ¡Â»â„¢n cÃ¡ÂºÂ£m L', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ tÃƒÂ­ch trÃ¡Â»Â¯ nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng.' }, { label: 'TÃ¡Â»Â¥ Ã„â€˜iÃ¡Â»â€¡n C', note: 'PhÃ¡ÂºÂ§n tÃ¡Â»Â­ tÃƒÂ­ch trÃ¡Â»Â¯ nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng.' }] },
  { key: 'cong suat dien xoay chieu', simulationType: 'rlc-3d', focus: 'NhÃƒÂ¬n sÃ¡Â»Â± lÃ¡Â»â€¡ch pha Ã„â€˜Ã¡Â»Æ’ hiÃ¡Â»Æ’u cÃƒÂ´ng suÃ¡ÂºÂ¥t tÃƒÂ¡c dÃ¡Â»Â¥ng.', components: [{ label: 'Ã„ÂiÃ¡Â»â€¡n ÃƒÂ¡p u', note: 'TÃƒÂ­n hiÃ¡Â»â€¡u nguÃ¡Â»â€œn xoay chiÃ¡Â»Âu tÃƒÂ¡c dÃ¡Â»Â¥ng lÃƒÂªn mÃ¡ÂºÂ¡ch.' }, { label: 'DÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n i', note: 'TÃƒÂ­n hiÃ¡Â»â€¡u Ã„â€˜ÃƒÂ¡p Ã¡Â»Â©ng cÃƒÂ³ thÃ¡Â»Æ’ lÃ¡Â»â€¡ch pha vÃ¡Â»â€ºi Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p.' }, { label: 'GÃƒÂ³c lÃ¡Â»â€¡ch pha Ãâ€ ', note: 'ThÃƒÂ´ng sÃ¡Â»â€˜ quyÃ¡ÂºÂ¿t Ã„â€˜Ã¡Â»â€¹nh hÃ¡Â»â€¡ sÃ¡Â»â€˜ cÃƒÂ´ng suÃ¡ÂºÂ¥t cosÃâ€ .' }] },
  { key: 'may bien ap', simulationType: 'transformer-3d', focus: 'Quan sÃƒÂ¡t liÃƒÂªn hÃ¡Â»â€¡ sÃ¡Â»â€˜ vÃƒÂ²ng dÃƒÂ¢y vÃƒÂ  Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p.', components: [{ label: 'CuÃ¡Â»â„¢n sÃ†Â¡ cÃ¡ÂºÂ¥p', note: 'CuÃ¡Â»â„¢n nhÃ¡ÂºÂ­n Ã„â€˜iÃ¡Â»â€¡n nÃ„Æ’ng tÃ¡Â»Â« nguÃ¡Â»â€œn xoay chiÃ¡Â»Âu.' }, { label: 'CuÃ¡Â»â„¢n thÃ¡Â»Â© cÃ¡ÂºÂ¥p', note: 'CuÃ¡Â»â„¢n nhÃ¡ÂºÂ­n cÃ¡ÂºÂ£m Ã¡Â»Â©ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡Â»Â« tÃ¡Â»Â« lÃƒÂµi chung.' }, { label: 'LÃƒÂµi sÃ¡ÂºÂ¯t tÃ¡Â»Â«', note: 'Ã„ÂÃ†Â°Ã¡Â»Âng dÃ¡ÂºÂ«n tÃ¡Â»Â« thÃƒÂ´ng giÃ¡Â»Â¯a hai cuÃ¡Â»â„¢n dÃƒÂ¢y.' }] },
  { key: 'truyen tai dien nang', simulationType: 'transformer-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh vai trÃƒÂ² tÃ„Æ’ng ÃƒÂ¡p Ã„â€˜Ã¡Â»Æ’ giÃ¡ÂºÂ£m hao phÃƒÂ­ trÃƒÂªn Ã„â€˜Ã†Â°Ã¡Â»Âng dÃƒÂ¢y.', components: [{ label: 'TrÃ¡ÂºÂ¡m tÃ„Æ’ng ÃƒÂ¡p', note: 'NÃ†Â¡i nÃƒÂ¢ng Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p trÃ†Â°Ã¡Â»â€ºc khi truyÃ¡Â»Ân Ã„â€˜i xa.' }, { label: 'Ã„ÂÃ†Â°Ã¡Â»Âng dÃƒÂ¢y tÃ¡ÂºÂ£i Ã„â€˜iÃ¡Â»â€¡n', note: 'PhÃ¡ÂºÂ§n mÃ¡ÂºÂ¡ng lÃ†Â°Ã¡Â»â€ºi chÃ¡Â»â€¹u hao phÃƒÂ­ nhiÃ¡Â»â€¡t do Ã„â€˜iÃ¡Â»â€¡n trÃ¡Â»Å¸.' }, { label: 'TrÃ¡ÂºÂ¡m hÃ¡ÂºÂ¡ ÃƒÂ¡p', note: 'NÃ†Â¡i Ã„â€˜Ã†Â°a Ã„â€˜iÃ¡Â»â€¡n ÃƒÂ¡p vÃ¡Â»Â mÃ¡Â»Â©c phÃƒÂ¹ hÃ¡Â»Â£p Ã„â€˜Ã¡Â»Æ’ sÃ¡Â»Â­ dÃ¡Â»Â¥ng.' }] },
  { key: 'mach dao dong lc', simulationType: 'rlc-3d', focus: 'Quan sÃƒÂ¡t nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng Ã„â€˜iÃ¡Â»â€¡n vÃƒÂ  tÃ¡Â»Â« luÃƒÂ¢n phiÃƒÂªn Ã„â€˜Ã¡Â»â€¢i chÃ¡Â»â€”.', components: [{ label: 'TÃ¡Â»Â¥ Ã„â€˜iÃ¡Â»â€¡n C', note: 'NÃ†Â¡i tÃƒÂ­ch Ã„â€˜iÃ¡Â»â€¡n vÃƒÂ  tÃ¡ÂºÂ¡o Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng.' }, { label: 'CuÃ¡Â»â„¢n cÃ¡ÂºÂ£m L', note: 'NÃ†Â¡i dÃƒÂ²ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡ÂºÂ¡o tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng.' }, { label: 'Trao Ã„â€˜Ã¡Â»â€¢i nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng', note: 'QuÃƒÂ¡ trÃƒÂ¬nh Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng vÃƒÂ  tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng biÃ¡ÂºÂ¿n Ã„â€˜Ã¡Â»â€¢i tuÃ¡ÂºÂ§n hoÃƒÂ n.' }] },
  { key: 'song dien tu', simulationType: 'magnetic-field-lines-3d', focus: 'Minh hÃ¡Â»Âa Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng vÃƒÂ  tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng vuÃƒÂ´ng gÃƒÂ³c cÃƒÂ¹ng lan truyÃ¡Â»Ân.', components: [{ label: 'VectÃ†Â¡ E', note: 'ThÃƒÂ nh phÃ¡ÂºÂ§n Ã„â€˜iÃ¡Â»â€¡n trÃ†Â°Ã¡Â»Âng dao Ã„â€˜Ã¡Â»â„¢ng trong sÃƒÂ³ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡Â»Â«.' }, { label: 'VectÃ†Â¡ B', note: 'ThÃƒÂ nh phÃ¡ÂºÂ§n tÃ¡Â»Â« trÃ†Â°Ã¡Â»Âng dao Ã„â€˜Ã¡Â»â„¢ng vuÃƒÂ´ng gÃƒÂ³c vÃ¡Â»â€ºi E.' }, { label: 'HÃ†Â°Ã¡Â»â€ºng truyÃ¡Â»Ân sÃƒÂ³ng', note: 'PhÃ†Â°Ã†Â¡ng lan truyÃ¡Â»Ân nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng cÃ¡Â»Â§a sÃƒÂ³ng Ã„â€˜iÃ¡Â»â€¡n tÃ¡Â»Â«.' }] },
  { key: 'hien tuong quang dien', simulationType: 'photoelectric-3d', focus: 'Theo dÃƒÂµi photon tÃ¡Â»â€ºi vÃƒÂ  electron bÃ¡ÂºÂ­t ra khÃ¡Â»Âi catot.', components: [{ label: 'Catot', note: 'BÃ¡Â»Â mÃ¡ÂºÂ·t kim loÃ¡ÂºÂ¡i phÃƒÂ¡t electron khi Ã„â€˜Ã†Â°Ã¡Â»Â£c chiÃ¡ÂºÂ¿u sÃƒÂ¡ng thÃƒÂ­ch hÃ¡Â»Â£p.' }, { label: 'Photon tÃ¡Â»â€ºi', note: 'GÃƒÂ³i nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng ÃƒÂ¡nh sÃƒÂ¡ng kÃƒÂ­ch hoÃ¡ÂºÂ¡t hiÃ¡Â»â€¡n tÃ†Â°Ã¡Â»Â£ng quang Ã„â€˜iÃ¡Â»â€¡n.' }, { label: 'Electron quang Ã„â€˜iÃ¡Â»â€¡n', note: 'HÃ¡ÂºÂ¡t bÃ¡ÂºÂ­t ra khÃ¡Â»Âi bÃ¡Â»Â mÃ¡ÂºÂ·t kim loÃ¡ÂºÂ¡i vÃƒÂ  tÃ¡ÂºÂ¡o dÃƒÂ²ng quang Ã„â€˜iÃ¡Â»â€¡n.' }] },
  { key: 'mau nguyen tu bohr', simulationType: 'bohr-atom-3d', focus: 'NhÃ¡ÂºÂ¥n mÃ¡ÂºÂ¡nh mÃ¡Â»Â©c nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng rÃ¡Â»Âi rÃ¡ÂºÂ¡c vÃƒÂ  bÃ†Â°Ã¡Â»â€ºc nhÃ¡ÂºÂ£y electron.', components: [{ label: 'HÃ¡ÂºÂ¡t nhÃƒÂ¢n', note: 'TÃƒÂ¢m nguyÃƒÂªn tÃ¡Â»Â­ mang Ã„â€˜iÃ¡Â»â€¡n dÃ†Â°Ã†Â¡ng.' }, { label: 'QuÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o mÃ¡Â»Â©c n', note: 'CÃƒÂ¡c mÃ¡Â»Â©c nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng Ã„â€˜Ã†Â°Ã¡Â»Â£c minh hÃ¡Â»Âa bÃ¡ÂºÂ±ng vÃƒÂ²ng quÃ¡Â»Â¹ Ã„â€˜Ã¡ÂºÂ¡o riÃƒÂªng.' }, { label: 'Photon phÃƒÂ¡t / hÃ¡ÂºÂ¥p thÃ¡Â»Â¥', note: 'BiÃ¡Â»Æ’u diÃ¡Â»â€¦n quÃƒÂ¡ trÃƒÂ¬nh electron nhÃ¡ÂºÂ£y mÃ¡Â»Â©c nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng.' }] },
  { key: 'tia x', simulationType: 'xray-tube-3d', focus: 'Cho thÃ¡ÂºÂ¥y electron tÃ„Æ’ng tÃ¡Â»â€˜c Ã„â€˜Ã¡ÂºÂ­p vÃƒÂ o anot sinh tia X.', components: [{ label: 'Catot phÃƒÂ¡t electron', note: 'NguÃ¡Â»â€œn cung cÃ¡ÂºÂ¥p electron trong Ã¡Â»â€˜ng tia X.' }, { label: 'Anot / bia kim loÃ¡ÂºÂ¡i', note: 'VÃ¡Â»â€¹ trÃƒÂ­ electron va Ã„â€˜Ã¡ÂºÂ­p Ã„â€˜Ã¡Â»Æ’ tÃ¡ÂºÂ¡o ra tia X.' }, { label: 'ChÃƒÂ¹m tia X', note: 'BÃ¡Â»Â©c xÃ¡ÂºÂ¡ phÃƒÂ¡t ra tÃ¡Â»Â« vÃƒÂ¹ng va chÃ¡ÂºÂ¡m nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng cao.' }] },
  { key: 'cau tao hat nhan', simulationType: 'nuclear-structure-3d', focus: 'TÃƒÂ¡ch rÃƒÂµ proton vÃƒÂ  neutron trong hÃ¡ÂºÂ¡t nhÃƒÂ¢n.', components: [{ label: 'Proton', note: 'HÃ¡ÂºÂ¡t mang Ã„â€˜iÃ¡Â»â€¡n dÃ†Â°Ã†Â¡ng cÃ¡ÂºÂ¥u tÃ¡ÂºÂ¡o nÃƒÂªn hÃ¡ÂºÂ¡t nhÃƒÂ¢n.' }, { label: 'Neutron', note: 'HÃ¡ÂºÂ¡t trung hÃƒÂ²a gÃƒÂ³p phÃ¡ÂºÂ§n Ã¡Â»â€¢n Ã„â€˜Ã¡Â»â€¹nh hÃ¡ÂºÂ¡t nhÃƒÂ¢n.' }, { label: 'LÃ¡Â»Â±c hÃ¡ÂºÂ¡t nhÃƒÂ¢n', note: 'TÃ†Â°Ã†Â¡ng tÃƒÂ¡c mÃ¡ÂºÂ¡nh giÃ¡Â»Â¯ nucleon liÃƒÂªn kÃ¡ÂºÂ¿t Ã¡Â»Å¸ phÃ¡ÂºÂ¡m vi rÃ¡ÂºÂ¥t ngÃ¡ÂºÂ¯n.' }] },
  { key: 'phong xa', simulationType: 'radioactive-decay-3d', focus: 'PhÃƒÂ¢n biÃ¡Â»â€¡t hÃ¡ÂºÂ¡t mÃ¡ÂºÂ¹, bÃ¡Â»Â©c xÃ¡ÂºÂ¡ phÃƒÂ¡t ra vÃƒÂ  bÃ¡Â»â„¢ Ã„â€˜Ã¡ÂºÂ¿m.', components: [{ label: 'HÃ¡ÂºÂ¡t nhÃƒÂ¢n mÃ¡ÂºÂ¹', note: 'HÃ¡ÂºÂ¡t nhÃƒÂ¢n khÃƒÂ´ng bÃ¡Â»Ân trÃ†Â°Ã¡Â»â€ºc khi phÃƒÂ¢n rÃƒÂ£.' }, { label: 'BÃ¡Â»Â©c xÃ¡ÂºÂ¡ phÃƒÂ¡t ra', note: 'CÃƒÂ³ thÃ¡Â»Æ’ lÃƒÂ  alpha, beta hoÃ¡ÂºÂ·c gamma tÃƒÂ¹y cÃ†Â¡ chÃ¡ÂºÂ¿ phÃƒÂ¢n rÃƒÂ£.' }, { label: 'Detector', note: 'BÃ¡Â»â„¢ phÃ¡ÂºÂ­n ghi nhÃ¡ÂºÂ­n sÃ¡Â»â€˜ hÃ¡ÂºÂ¡t hoÃ¡ÂºÂ·c tia phÃƒÂ¡t ra.' }] },
  { key: 'phan ung hat nhan', simulationType: 'nuclear-reaction-3d', focus: 'Quan sÃƒÂ¡t hÃ¡ÂºÂ¡t bÃ¡ÂºÂ¯n phÃƒÂ¡, hÃ¡ÂºÂ¡t Ã„â€˜ÃƒÂ­ch vÃƒÂ  sÃ¡ÂºÂ£n phÃ¡ÂºÂ©m phÃ¡ÂºÂ£n Ã¡Â»Â©ng.', components: [{ label: 'HÃ¡ÂºÂ¡t bÃ¡ÂºÂ¯n phÃƒÂ¡', note: 'HÃ¡ÂºÂ¡t tÃ¡Â»â€ºi gÃƒÂ¢y ra phÃ¡ÂºÂ£n Ã¡Â»Â©ng hÃ¡ÂºÂ¡t nhÃƒÂ¢n.' }, { label: 'HÃ¡ÂºÂ¡t nhÃƒÂ¢n Ã„â€˜ÃƒÂ­ch', note: 'HÃ¡ÂºÂ¡t nhÃƒÂ¢n ban Ã„â€˜Ã¡ÂºÂ§u nhÃ¡ÂºÂ­n va chÃ¡ÂºÂ¡m.' }, { label: 'SÃ¡ÂºÂ£n phÃ¡ÂºÂ©m phÃ¡ÂºÂ£n Ã¡Â»Â©ng', note: 'CÃƒÂ¡c hÃ¡ÂºÂ¡t hay hÃ¡ÂºÂ¡t nhÃƒÂ¢n tÃ¡ÂºÂ¡o thÃƒÂ nh sau phÃ¡ÂºÂ£n Ã¡Â»Â©ng.' }] },
  { key: 'nang luong lien ket', simulationType: 'binding-energy-3d', focus: 'Minh hÃ¡Â»Âa giÃ¡ÂºÂ¿ng thÃ¡ÂºÂ¿ vÃƒÂ  Ã„â€˜Ã¡Â»â„¢ hÃ¡Â»Â¥t khÃ¡Â»â€˜i cÃ¡Â»Â§a hÃ¡ÂºÂ¡t nhÃƒÂ¢n.', components: [{ label: 'GiÃ¡ÂºÂ¿ng thÃ¡ÂºÂ¿ nÃ„Æ’ng', note: 'VÃƒÂ¹ng nÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng ÃƒÂ¢m biÃ¡Â»Æ’u diÃ¡Â»â€¦n trÃ¡ÂºÂ¡ng thÃƒÂ¡i liÃƒÂªn kÃ¡ÂºÂ¿t bÃ¡Â»Ân.' }, { label: 'Nucleon liÃƒÂªn kÃ¡ÂºÂ¿t', note: 'CÃƒÂ¡c hÃ¡ÂºÂ¡t bÃ¡Â»â€¹ giÃ¡Â»Â¯ trong hÃ¡ÂºÂ¡t nhÃƒÂ¢n bÃ¡Â»Å¸i lÃ¡Â»Â±c hÃ¡ÂºÂ¡t nhÃƒÂ¢n.' }, { label: 'NÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng tÃƒÂ¡ch', note: 'NÃ„Æ’ng lÃ†Â°Ã¡Â»Â£ng cÃ¡ÂºÂ§n cung cÃ¡ÂºÂ¥p Ã„â€˜Ã¡Â»Æ’ phÃƒÂ¡ liÃƒÂªn kÃ¡ÂºÂ¿t hÃ¡ÂºÂ¡t nhÃƒÂ¢n.' }] }
];

export function resolveLessonSimulationBlueprint(input: { title?: string; slug?: string; topic?: string; type?: string }) {
  const haystack = normalize(`${input.title || ''} ${input.slug || ''} ${input.topic || ''}`);
  const exact = BLUEPRINTS.find((item) => haystack.includes(item.key));
  if (exact) return { ...exact, matched: true };

  const fallbackType = input.type || 'co-hoc-overview-visual';
  return {
    key: haystack || 'default',
    simulationType: fallbackType,
    focus: 'Quan sÃƒÂ¡t cÃƒÂ¡c thÃƒÂ nh phÃ¡ÂºÂ§n chÃƒÂ­nh cÃ¡Â»Â§a mÃƒÂ´ phÃ¡Â»Âng, Ã„â€˜Ã¡Â»â€˜i chiÃ¡ÂºÂ¿u vÃ¡Â»â€ºi cÃƒÂ´ng thÃ¡Â»Â©c lÃƒÂµi rÃ¡Â»â€œi mÃ¡Â»â€ºi thay tham sÃ¡Â»â€˜.',
    components: [
      { label: 'ThÃƒÂ nh phÃ¡ÂºÂ§n trung tÃƒÂ¢m', note: 'Ã„ÂÃ¡Â»â€˜i tÃ†Â°Ã¡Â»Â£ng chÃƒÂ­nh cÃ¡ÂºÂ§n theo dÃƒÂµi trong bÃƒÂ i hÃ¡Â»Âc nÃƒÂ y.' },
      { label: 'Tham sÃ¡Â»â€˜ Ã„â€˜iÃ¡Â»Âu khiÃ¡Â»Æ’n', note: 'BiÃ¡ÂºÂ¿n sÃ¡Â»â€˜ lÃƒÂ m thay Ã„â€˜Ã¡Â»â€¢i trÃ¡ÂºÂ¡ng thÃƒÂ¡i hoÃ¡ÂºÂ·c quy luÃ¡ÂºÂ­t cÃ¡Â»Â§a mÃƒÂ´ phÃ¡Â»Âng.' },
      { label: 'DÃ¡ÂºÂ¥u hiÃ¡Â»â€¡u quan sÃƒÂ¡t', note: 'Chi tiÃ¡ÂºÂ¿t cÃ¡ÂºÂ§n Ã„â€˜Ã¡Â»Âc Ã„â€˜Ã¡Â»Æ’ suy ra bÃ¡ÂºÂ£n chÃ¡ÂºÂ¥t vÃ¡ÂºÂ­t lÃƒÂ½ cÃ¡Â»Â§a hiÃ¡Â»â€¡n tÃ†Â°Ã¡Â»Â£ng.' }
    ],
    matched: false
  };
}
